name: Auto_Wasm_Compiler
on:
  push:
    branches: [ main ] 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v11

      - name: Compile C++ to Wasm
        run: |
          emcc main.cpp gravity.cpp -o bridge.js -s EXPORTED_FUNCTIONS='["_main", "_get_dimensions", "_get_positions", "_get_colors", "_add_cube_to_logic"]' -s EXPORTED_RUNTIME_METHODS='["ccall","cwrap"]' -s NO_EXIT_RUNTIME=1

      - name: Upload Result
        uses: actions/upload-artifact@v3
        with:
          name: wasm-files
          path: |
            bridge.js
            bridge.wasm
